[package]
name = "conway"
version = "0.1.0"
authors = ["jawer"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.6.0"
rand = "0.8.4"
winit = "0.25.0"
